/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;
import view.GUIHistoria;
import view.GUICreditos;
import view.GUIInstrucciones;
import view.GUIJuego;
import model.Sonidos;

/**
 *
 * @author TI-IN
 */
public class GUIInicio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIInicio.class.getName());

    /**
     * Creates new form GUIInicio
     */
    private Sonidos sonido;

    public GUIInicio() {
        initComponents();
        sonido.musicaFondoPrincipal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboColor = new javax.swing.JComboBox<>();
        IbiSeleccion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnJugar = new javax.swing.JButton();
        btnHistoria = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        imgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboColor.setBackground(new java.awt.Color(0, 153, 204));
        comboColor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        comboColor.setForeground(new java.awt.Color(255, 255, 255));
        comboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Amarillo", "Azul", "Verde" }));
        comboColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboColorActionPerformed(evt);
            }
        });
        getContentPane().add(comboColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        IbiSeleccion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        IbiSeleccion.setForeground(new java.awt.Color(255, 255, 255));
        IbiSeleccion.setText("Selección de color");
        getContentPane().add(IbiSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Imágenes de referencia-20251014/boton.png"))); // NOI18N
        btnJugar.setBorderPainted(false);
        btnJugar.setContentAreaFilled(false);
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        jPanel1.add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        btnHistoria.setBackground(new java.awt.Color(0, 153, 204));
        btnHistoria.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnHistoria.setForeground(new java.awt.Color(255, 255, 255));
        btnHistoria.setText("Historia");
        btnHistoria.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriaActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 130, 30));

        btnInstrucciones.setBackground(new java.awt.Color(0, 153, 204));
        btnInstrucciones.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        btnInstrucciones.setText("Instrucciones");
        btnInstrucciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruccionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 130, 30));

        btnCreditos.setBackground(new java.awt.Color(0, 153, 204));
        btnCreditos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnCreditos.setForeground(new java.awt.Color(255, 255, 255));
        btnCreditos.setText("Créditos");
        btnCreditos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 130, 30));

        imgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Imágenes de referencia-20251014/imgInicio_1.png"))); // NOI18N
        jPanel1.add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 510, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
        int colorId = comboColor.getSelectedIndex();

        Controller ctrl = new Controller(colorId);

        GUIJuego v2 = new GUIJuego(ctrl);   // <-- Pásalo por el constructor
        v2.setLocationRelativeTo(null);
        v2.setVisible(true);
        this.dispose();
        sonido.click();
        sonido.detenerFondo();
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruccionesActionPerformed
        // TODO add your handling code here:

        GUIInstrucciones demo = new GUIInstrucciones();
        demo.setVisible(true);
        demo.setLocationRelativeTo(null);

        this.setVisible(false);
        sonido.click();
        sonido.detenerFondo();
    }//GEN-LAST:event_btnInstruccionesActionPerformed

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
        // TODO add your handling code here:
        GUICreditos demo = new GUICreditos();
        demo.setVisible(true);
        demo.setLocationRelativeTo(null);

        this.setVisible(false);

        sonido.click();
        sonido.detenerFondo();
    }//GEN-LAST:event_btnCreditosActionPerformed

    private void comboColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboColorActionPerformed

    private void btnHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaActionPerformed
        // TODO add your handling code here:
        GUIHistoria demo = new GUIHistoria();
        demo.setVisible(true);
        demo.setLocationRelativeTo(null);

        this.setVisible(false);
        sonido.click();
        sonido.detenerFondo();
    }//GEN-LAST:event_btnHistoriaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IbiSeleccion;
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnHistoria;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JComboBox<String> comboColor;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
