/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import model.TableroCoordenadas;

/**
 *
 * @author EMILI VALERIA
 */
public class PanelTablero extends javax.swing.JPanel {

    /**
     * Creates new form PanelTablero
     */
    private TableroCoordenadas tablero;
    public PanelTablero() {
        initComponents();
//        this.addMouseListener(new MouseAdapter() {
//            @Override
//            public void mousePressed(MouseEvent e) {
//                Point p = e.getPoint();
//                clickFicha(p);
//            }//fin metodo
//        });
    }

    public JLabel getImgFichaAmarillo() {
        return imgFichaAmarillo;
    }

    
    public JLabel getImgFichaAzul() {
        return imgFichaAzul;
    }

    public JLabel getImgFichaRojo() {
        return imgFichaRojo;
    }

    public JLabel getImgFichaVerde() {
        return imgFichaVerde;
    }
   

    public JLabel getImgTablero() {
        return imgTablero;
    }

    public void setTablero(TableroCoordenadas tablero) {
        this.tablero = tablero;
    }

    public void setImgTablero(JLabel imgTablero) {
        this.imgTablero = imgTablero;
    }

   

    
    public void setTableroCoordenadas(TableroCoordenadas tablero) {

        this.tablero = tablero;

    }//fin setTableroCoordenadas

//    public void clickFicha(Point p) {
//        imgFichaRoja.setLocation(p);
//        System.out.println("Coordenadas :" + p.x + " , " + p.y + ".");
//    }

    public void moverFicha(int colorId, int x, int y) {
        JLabel lbl = labelJugador(colorId);
        if (lbl != null) {
            lbl.setLocation(x, y);
            lbl.repaint();
            this.repaint();
        }//fin if
    }

    public JLabel labelJugador(int colorId) {
        if (colorId == 0) {
            return imgFichaRojo;
        }
        if (colorId == 1) {
            return imgFichaAmarillo;
        }//fin if2
        if (colorId == 2) {
            return imgFichaAzul;
        }//fin if3

       if (colorId == 3)
    {
        return imgFichaVerde;
    }
        return imgFichaRojo;

    }//fin

//    public void repintar(int x, int y) {
//        imgFichaRoja.setLocation(x, y);
//        imgFichaRoja.repaint();
//    }//fin repintar

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                        
                          

    
    // End of variables declaration                   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgFichaAmarillo = new javax.swing.JLabel();
        imgFichaAzul = new javax.swing.JLabel();
        imgFichaVerde = new javax.swing.JLabel();
        imgFichaRojo = new javax.swing.JLabel();
        imgTablero = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgFichaAmarillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Recursos de ejemplo para proyecto-20251021/FichaAmarilla.png"))); // NOI18N
        add(imgFichaAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        imgFichaAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Recursos de ejemplo para proyecto-20251021/FichaAzul.png"))); // NOI18N
        add(imgFichaAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        imgFichaVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Recursos de ejemplo para proyecto-20251021/FichaVerde.png"))); // NOI18N
        add(imgFichaVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        imgFichaRojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Recursos de ejemplo para proyecto-20251021/FichaRoja.png"))); // NOI18N
        add(imgFichaRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, -1, -1));

        imgTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Recursos de ejemplo para proyecto-20251021/tablerografico.png"))); // NOI18N
        add(imgTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgFichaAmarillo;
    private javax.swing.JLabel imgFichaAzul;
    private javax.swing.JLabel imgFichaRojo;
    private javax.swing.JLabel imgFichaVerde;
    private javax.swing.JLabel imgTablero;
    // End of variables declaration//GEN-END:variables
}
