/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author EMILI VALERIA
 */
public class PanelControl extends javax.swing.JPanel {

    /**
     * Creates new form PanelTablero
     */
    public PanelControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDado = new javax.swing.JButton();
        btnReinicio = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        lblNumeroDado = new javax.swing.JLabel();
        lblFichaTurno = new javax.swing.JLabel();

        btnDado.setText("Dado");

        btnReinicio.setText("Reinicio");

        btnMenu.setText("Menú");

        lblNumeroDado.setText("Número Dado");

        lblFichaTurno.setText("Ficha Turno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFichaTurno)
                    .addComponent(btnMenu)
                    .addComponent(btnReinicio)
                    .addComponent(btnDado)
                    .addComponent(lblNumeroDado))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDado)
                .addGap(18, 18, 18)
                .addComponent(lblNumeroDado)
                .addGap(18, 18, 18)
                .addComponent(lblFichaTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(btnReinicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenu)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDado;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnReinicio;
    private javax.swing.JLabel lblFichaTurno;
    private javax.swing.JLabel lblNumeroDado;
    // End of variables declaration//GEN-END:variables
}
