/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author EMILI VALERIA
 */
public class PanelTablero extends javax.swing.JPanel {

    /**
     * Creates new form PanelTablero
     */
    public PanelTablero() {
        initComponents();
        //MouseAdapter
        
        this.addMouseListener(new MouseAdapter ()
                {
                    @Override
                    public void mousePressed (MouseEvent e)
                    {
                    Point p = e.getPoint();
                    moverFicha(p);
                    }//fin metodo
                });
    }

    public void moverFicha (Point p)
    {
       imgFicha.setLocation(p);
       System.out.println("Coordenadas :" + p.x + " , "+ p.y +".");
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        imgFichaAzul = new javax.swing.JLabel();
        imgFichaVerde = new javax.swing.JLabel();
        imgFicha = new javax.swing.JLabel();
        imgTablero = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Recursos de ejemplo para proyecto-20251021/FichaAmarilla.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        imgFichaAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Recursos de ejemplo para proyecto-20251021/FichaAzul.png"))); // NOI18N
        add(imgFichaAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        imgFichaVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Recursos de ejemplo para proyecto-20251021/FichaVerde.png"))); // NOI18N
        add(imgFichaVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        imgFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Recursos de ejemplo para proyecto-20251021/FichaRoja.png"))); // NOI18N
        add(imgFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, -1, -1));

        imgTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Recursos de ejemplo para proyecto-20251021/tablerografico.png"))); // NOI18N
        add(imgTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgFicha;
    private javax.swing.JLabel imgFichaAzul;
    private javax.swing.JLabel imgFichaVerde;
    private javax.swing.JLabel imgTablero;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
